### PR TITLE
Fix webpack issue

### PR DESCRIPTION
**Pull request by GavinQ1**

### CODE REVIEW

**Comment by jodeleeuw** [comment]
`npm run build` is still failing for me 🙁

**Comment by jodeleeuw** [comment]
image

**Comment by GavinQ1** [comment]
@jodeleeuw , use npm start. I haven't written production config yet

**Comment by jodeleeuw** [comment]
That fails for me too.

image

**Comment by GavinQ1** [comment]
Have you installed babel-cli?

**Comment by jodeleeuw** [comment]
I ran what the error message suggested and that worked:

```
npm uninstall babel
npm install --save-dev babel-cli
```

This changes package.json a bit (adds bable-cli as dev dependency), but I'm not going to push it right now.

**Comment by GavinQ1** [comment]
Don't worry. That is in the package.json already

**Pull request merged**
